/* eslint-disable */
/**
 * This file was automatically generated by `npm run gen:types`.
 *
 * DO NOT EDIT BY HAND. It is derived from the `witness-core` serde wire
 * types via schemars JSON Schema (sdk/ts/schema/schema.json) and
 * json-schema-to-typescript. Regenerate with:
 *
 *   cargo run -p witness-core --bin gen_ts_types   # emits schema.json
 *   npm run gen:types                              # emits types.generated.ts
 *
 * CI enforces a zero-diff drift gate: any change to the serde wire types
 * must be accompanied by a regenerated file, otherwise `npm run check:types`
 * fails.
 */

export type WitnessWireTypes =
  | AnchorProviderConfig
  | AnchorProviderType
  | Attestation
  | AttestationBatch
  | AttestationEvent
  | AttestationJobResponse
  | AttestationJobStatus
  | AttestationSignatures
  | BatchInclusion
  | CreateAttestationRequest
  | CrossAnchor
  | ExternalAnchorProof
  | ExternalAnchorsConfig
  | FederationConfig
  | FederationVerificationConfig
  | FreebirdToken
  | LogConsistencyProof
  | LogInclusionProofResponse
  | MerkleProof
  | MerkleProofResponse
  | NetworkConfig
  | NetworkConfigPublic
  | NetworkVerificationConfig
  | PeerNetworkInfo
  | PeerNetworkVerificationInfo
  | ProofBundle
  | ProofBundleVerification
  | ProofVerificationConfig
  | SignatureScheme
  | SignedAttestation
  | SignedTreeHead
  | TimestampRequest
  | TimestampResponse
  | TreeHead
  | U64
  | VerificationLevel
  | VerificationWitnessInfo
  | VerifyRequest
  | VerifyResponse
  | WitnessInfo
  | WitnessSignature;
/**
 * External anchor provider types
 */
export type AnchorProviderType = "internet_archive" | "trillian" | "dns_txt" | "blockchain";
/**
 * Signatures on an attestation (multi-sig or aggregated)
 */
export type AttestationSignatures =
  | {
      signature?: never;
      signatures: WitnessSignature[];
      signers?: never;
    }
  | {
      /**
       * Aggregated BLS signature (48 bytes / 96 lowercase hex characters).
       */
      signature: string;
      signatures?: never;
      /**
       * List of witness IDs that participated
       */
      signers: string[];
    };
/**
 * Durable lifecycle state of an attestation job.
 */
export type AttestationJobStatus = "pending" | "retryable" | "confirmed" | "failed";
/**
 * Signature scheme used by the network
 */
export type SignatureScheme = "ed25519" | "bls";
/**
 * Level of verification achieved
 */
export type VerificationLevel =
  | "None"
  | "Basic"
  | "Batched"
  | {
      Federated: {
        peer_count: number;
      };
    };
export type U64 = number | bigint;

/**
 * Configuration for an external anchor provider
 */
export interface AnchorProviderConfig {
  /**
   * Whether this provider is enabled
   */
  enabled?: boolean;
  /**
   * Priority (lower = higher priority, providers tried in order)
   */
  priority?: number;
  /**
   * Type of anchor provider
   */
  type: AnchorProviderType;
}
/**
 * Core attestation: what gets signed by witnesses
 */
export interface Attestation {
  /**
   * SHA-256 hash of the content being timestamped
   */
  hash: string;
  /**
   * Which Witness network this attestation is from
   */
  network_id: string;
  /**
   * Monotonic sequence number for ordering
   */
  sequence: U64;
  /**
   * Unix timestamp in seconds
   */
  timestamp: U64;
}
/**
 * A batch of attestations with their merkle root
 */
export interface AttestationBatch {
  /**
   * Number of attestations in this batch
   */
  attestation_count: U64;
  /**
   * Unique batch ID
   */
  id: U64;
  /**
   * Merkle root of all attestations in this batch
   */
  merkle_root: string;
  /**
   * Network that created this batch
   */
  network_id: string;
  /**
   * End of batch period (Unix seconds)
   */
  period_end: U64;
  /**
   * Start of batch period (Unix seconds)
   */
  period_start: U64;
}
/**
 * Event broadcast to WebSocket clients when an attestation is created.
 */
export interface AttestationEvent {
  hash: string;
  timestamp: U64;
  type: string;
}
/**
 * Stable snapshot returned when creating or reading an attestation job.
 *
 * The canonical tuple is always present. `signed_attestation` is present only after the job has reached `confirmed`; pending and failed jobs never expose an unsigned `SignedAttestation` placeholder.
 */
export interface AttestationJobResponse {
  /**
   * Number of leases issued for this job.
   */
  attempts: number;
  attestation: Attestation;
  last_error?: string | null;
  /**
   * Unix timestamp at which a pending/retryable job is next eligible.
   */
  next_attempt_at?: U64 | null;
  signed_attestation?: SignedAttestation | null;
  status: AttestationJobStatus;
}
/**
 * Complete signed attestation with all witness signatures
 */
export interface SignedAttestation {
  attestation: Attestation;
  /**
   * Signatures (multi-sig or aggregated)
   */
  signatures: AttestationSignatures;
}
/**
 * A single witness's signature on an attestation
 */
export interface WitnessSignature {
  /**
   * Signature bytes (Ed25519 64 bytes or BLS 48 bytes / 96 lowercase hex characters, depending on network configuration).
   */
  signature: string;
  /**
   * ID of the witness that signed
   */
  witness_id: string;
}
/**
 * Inclusion of an attestation in a batch's merkle tree.
 */
export interface BatchInclusion {
  batch: AttestationBatch;
  merkle_proof: MerkleProof;
}
/**
 * Inclusion proof for a single leaf at `leaf_index` in a tree of size `tree_size`.  The siblings are listed bottom-up (leaf level first).
 */
export interface MerkleProof {
  /**
   * The raw leaf bytes (pre-hash).  `hash_leaf(leaf)` is the value at position `leaf_index` in the tree.
   */
  leaf: string;
  /**
   * 0-based position of `leaf` in the log.  Renamed from `index` so callers are forced to update for the position-aware verifier.
   */
  leaf_index: U64;
  /**
   * Root hash of the tree at `tree_size`.  Carried for convenience; the verifier may also pass an externally trusted root and ignore this.
   */
  root: string;
  /**
   * Audit path: sibling hashes from leaf level upward to (but not including) the root.
   */
  siblings: string[];
  /**
   * Total number of leaves in the tree this proof was generated against. Required to walk the unbalanced-split tree shape.
   */
  tree_size: U64;
}
/**
 * Request to create or retrieve the canonical attestation job for a hash.
 */
export interface CreateAttestationRequest {
  /**
   * Optional Freebird token for Sybil resistance.
   */
  freebird_token?: FreebirdToken | null;
  /**
   * SHA-256 hash to attest (hex encoded).
   */
  hash: string;
}
/**
 * Freebird token for anonymous authorization
 */
export interface FreebirdToken {
  /**
   * Base64url-encoded Freebird redemption token.
   */
  token_b64: string;
}
/**
 * Cross-anchor attestation from a peer network.
 *
 * The peer network signs an [`Attestation`](crate::Attestation) whose `hash` is the cross-anchored batch's merkle root and whose `network_id` is the peer's own network ID.  This makes the cross-anchor a self-contained, independently verifiable threshold signature — clients can verify it against the peer's published [`NetworkVerificationConfig`] without trusting the originating gateway.
 */
export interface CrossAnchor {
  /**
   * The batch being witnessed
   */
  batch: AttestationBatch;
  /**
   * When this cross-anchor was created (Unix seconds)
   */
  timestamp: U64;
  /**
   * Signed attestation from the peer network over `batch.merkle_root`
   */
  witness_attestation: SignedAttestation;
  /**
   * ID of the network that witnessed this batch
   */
  witnessing_network: string;
}
/**
 * Proof that data was anchored to an external service
 */
export interface ExternalAnchorProof {
  /**
   * Optional: the actual data that was anchored (for verification)
   */
  anchored_data?: number[] | null;
  /**
   * Provider-specific proof data (URL, transaction hash, etc.)
   */
  proof: {
    [k: string]: unknown;
  };
  /**
   * Type of anchor provider
   */
  provider: AnchorProviderType;
  /**
   * When this anchor was created
   */
  timestamp: U64;
}
/**
 * Configuration for external anchoring
 */
export interface ExternalAnchorsConfig {
  /**
   * How often to anchor batches (seconds)
   */
  anchor_period?: U64;
  /**
   * Whether external anchoring is enabled
   */
  enabled?: boolean;
  /**
   * Minimum number of successful anchors required
   */
  minimum_required?: number;
  /**
   * List of anchor providers
   */
  providers?: AnchorProviderConfig[];
}
/**
 * Configuration for federation
 */
export interface FederationConfig {
  /**
   * How often to close batches (seconds)
   */
  batch_period?: U64;
  /**
   * Minimum number of peer networks that must cross-anchor
   */
  cross_anchor_threshold?: number;
  /**
   * Whether federation is enabled
   */
  enabled?: boolean;
  /**
   * Peer networks to federate with
   */
  peer_networks?: PeerNetworkInfo[];
}
/**
 * Information about a peer network
 */
export interface PeerNetworkInfo {
  /**
   * Gateway URL for this peer network
   */
  gateway: string;
  /**
   * Peer network ID
   */
  id: string;
  /**
   * Minimum number of witnesses required from this peer
   */
  min_witnesses?: number;
}
/**
 * Public federation discovery and policy fields used by verifiers.
 *
 * This is deliberately separate from [`FederationConfig`]: it contains no batch scheduling state or inbound authentication material.
 */
export interface FederationVerificationConfig {
  /**
   * Number of distinct configured peers required for a federated result.
   */
  cross_anchor_threshold?: number;
  /**
   * Whether cross-anchoring is enabled for this network.
   */
  enabled?: boolean;
  /**
   * Public gateway discovery information for configured peers.
   */
  peer_networks?: PeerNetworkVerificationInfo[];
}
/**
 * Public discovery and verification policy for one federation peer.
 */
export interface PeerNetworkVerificationInfo {
  /**
   * Public gateway URL used to discover the peer's verification config.
   */
  gateway: string;
  /**
   * Peer network ID.
   */
  id: string;
  /**
   * Minimum number of signatures required from this peer network.
   */
  min_witnesses?: number;
}
/**
 * Consistency proof linking two signed tree heads of the same log.
 */
export interface LogConsistencyProof {
  /**
   * Hashes from RFC 9162 §2.1.4.1 PROOF.
   */
  hashes: string[];
  new_sth: SignedTreeHead;
  old_sth: SignedTreeHead;
}
/**
 * A [`TreeHead`] together with witness threshold signatures over its digest.  The same `AttestationSignatures` machinery used for individual timestamps is reused; verification piggybacks on [`crate::verify_signed_attestation`].
 */
export interface SignedTreeHead {
  signed_attestation: SignedAttestation;
  tree_head: TreeHead;
}
/**
 * Plaintext fields of a tree head.  The signing digest commits to all of these so a verifier given a [`SignedTreeHead`] can recompute it.
 */
export interface TreeHead {
  /**
   * Network this STH belongs to.
   */
  network_id: string;
  /**
   * Merkle root of the log at `tree_size`.
   */
  root_hash: string;
  /**
   * When this STH was issued (Unix seconds).
   */
  timestamp: U64;
  /**
   * Number of leaves in the log.
   */
  tree_size: U64;
}
/**
 * RFC 9162 §4.11 inclusion proof response (`GET /v1/log/proof`).
 */
export interface LogInclusionProofResponse {
  audit_path: string[];
  leaf_index: U64;
  sth: SignedTreeHead;
  tree_size: U64;
}
/**
 * Response for a Merkle inclusion proof (`GET /v1/proof/:hash`).
 */
export interface MerkleProofResponse {
  batch_id: U64;
  hash: string;
  index: number;
  merkle_root: string;
  proof: string[];
}
/**
 * Network configuration
 */
export interface NetworkConfig {
  /**
   * External anchors configuration (Phase 3)
   */
  external_anchors?: ExternalAnchorsConfig;
  /**
   * Federation configuration (Phase 2)
   */
  federation?: FederationConfig;
  /**
   * Deprecated: Use federation.peer_networks instead
   */
  federation_peers?: string[];
  /**
   * Network identifier
   */
  id: string;
  /**
   * Signature scheme (ed25519 or bls)
   */
  signature_scheme?: SignatureScheme & string;
  /**
   * Minimum number of signatures required
   */
  threshold: number;
  /**
   * List of witnesses in this network
   */
  witnesses: WitnessInfo[];
}
/**
 * Information about a witness node
 */
export interface WitnessInfo {
  /**
   * HTTP endpoint for this witness
   */
  endpoint: string;
  /**
   * Unique identifier for this witness
   */
  id: string;
  /**
   * Public key (Ed25519 32 bytes or BLS 96 bytes / 192 lowercase hex characters, hex encoded).
   */
  pubkey: string;
}
/**
 * Public-facing subset of [`NetworkConfig`] — excludes internal endpoints, peer URLs, and auth tokens. Returned by `GET /v1/config`.
 */
export interface NetworkConfigPublic {
  id: string;
  signature_scheme: SignatureScheme;
  threshold: number;
  witness_count: number;
}
/**
 * Secret-free trust anchor for verifying attestations, STHs, and proof bundles.  Operator `network.json` files are intentionally accepted as a superset when deserializing this type: unknown operational fields are ignored by serde, allowing offline tools to load existing files without exposing those fields in the verification model.
 */
export interface NetworkVerificationConfig {
  /**
   * Public federation discovery and policy.
   */
  federation?: FederationVerificationConfig;
  /**
   * Network identifier pinned into signed attestations.
   */
  id: string;
  /**
   * Signature scheme used by this network.
   */
  signature_scheme?: SignatureScheme & string;
  /**
   * Minimum number of witness signatures required.
   */
  threshold: number;
  /**
   * Witness identities and public keys.
   */
  witnesses: VerificationWitnessInfo[];
}
/**
 * Public witness identity used by a [`NetworkVerificationConfig`].
 *
 * Unlike [`WitnessInfo`], this DTO has no endpoint or authentication token.
 */
export interface VerificationWitnessInfo {
  /**
   * Unique witness identifier.
   */
  id: string;
  /**
   * Public key (Ed25519 32 bytes or BLS 96 bytes / 192 lowercase hex characters, hex encoded).
   */
  pubkey: string;
}
/**
 * Self-contained bundle proving the full chain of trust for a hash.
 *
 * All four layers are independently verifiable, so a client can confirm: - **Threshold signature** — the home network's witnesses signed the attestation. - **Batch inclusion** — the attestation was committed to a merkle root. - **Cross-anchors** — peer networks signed that root. - **External anchors** — the root was committed to external systems (Internet Archive, Trillian, DNS, blockchain).
 */
export interface ProofBundle {
  /**
   * Merkle inclusion proof, present once the attestation has been batched
   */
  batch_inclusion?: BatchInclusion | null;
  /**
   * Cross-anchors from peer networks
   */
  cross_anchors?: CrossAnchor[];
  /**
   * External anchor proofs (Internet Archive, Trillian, DNS, blockchain)
   */
  external_anchors?: ExternalAnchorProof[];
  /**
   * Threshold-signed attestation from the home network
   */
  signed_attestation: SignedAttestation;
}
/**
 * Result of verifying a [`ProofBundle`].
 */
export interface ProofBundleVerification {
  /**
   * Whether the merkle inclusion proof verified, if present
   */
  batch_inclusion_verified?: boolean | null;
  /**
   * Per-peer verification status: `(witnessing_network, verified)`
   */
  cross_anchors_verified: [string, boolean][];
  /**
   * Number of external anchor proofs included (not cryptographically verified here)
   */
  external_anchors_present: number;
  /**
   * Highest level of verification achieved
   */
  level: VerificationLevel;
  /**
   * Threshold required by the home network
   */
  required_signatures: number;
  /**
   * Number of valid signatures on the threshold-signed attestation
   */
  verified_signatures: number;
}
/**
 * Configuration for verifying a [`ProofBundle`] offline.
 */
export interface ProofVerificationConfig {
  /**
   * The home network's configuration (used to verify the threshold signature)
   */
  network: NetworkVerificationConfig;
  /**
   * Peer network configurations (used to verify cross-anchors). Cross-anchors from networks not present here are reported as unverified.
   */
  peers: NetworkVerificationConfig[];
}
/**
 * Request to timestamp a hash
 */
export interface TimestampRequest {
  /**
   * Optional Freebird token for Sybil resistance
   */
  freebird_token?: FreebirdToken | null;
  /**
   * SHA-256 hash to timestamp (hex encoded)
   */
  hash: string;
}
/**
 * Response from successful timestamp request
 */
export interface TimestampResponse {
  attestation: SignedAttestation;
  status?: string;
}
/**
 * Request to verify an attestation
 */
export interface VerifyRequest {
  attestation: SignedAttestation;
}
/**
 * Response from verification
 */
export interface VerifyResponse {
  message: string;
  required_signatures: number;
  valid: boolean;
  verified_signatures: number;
}
