// TypeScript type-generation script for `@witness/sdk`.
//
// Reads the combined JSON Schema emitted by the Rust generator
// (`cargo run -p witness-core --bin gen_ts_types` -> sdk/ts/schema/schema.json)
// and runs `json-schema-to-typescript` to produce `src/types.generated.ts`.
//
// The generated file is checked in. CI enforces a zero-diff drift gate via
// `npm run check:types` (regenerate && git diff --exit-code).

import { compileFromFile } from 'json-schema-to-typescript';
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const schemaPath = path.join(root, 'schema', 'schema.json');
const outPath = path.join(root, 'src', 'types.generated.ts');

const banner = [
  '/* eslint-disable */',
  '/**',
  ' * This file was automatically generated by `npm run gen:types`.',
  ' *',
  ' * DO NOT EDIT BY HAND. It is derived from the `witness-core` serde wire',
  ' * types via schemars JSON Schema (sdk/ts/schema/schema.json) and',
  ' * json-schema-to-typescript. Regenerate with:',
  ' *',
  ' *   cargo run -p witness-core --bin gen_ts_types   # emits schema.json',
  ' *   npm run gen:types                              # emits types.generated.ts',
  ' *',
  ' * CI enforces a zero-diff drift gate: any change to the serde wire types',
  ' * must be accompanied by a regenerated file, otherwise `npm run check:types`',
  ' * fails.',
  ' */',
  '',
].join('\n');

const ts = await compileFromFile(schemaPath, {
  bannerComment: banner,
  cwd: path.dirname(schemaPath),
  additionalProperties: false,
});

await mkdir(path.dirname(outPath), { recursive: true });
await writeFile(outPath, ts);
console.log(`Wrote ${outPath}`);
